{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "gpu-stats-collector.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "gpu-stats-collector.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "rolebindings","nodes"]
  verbs: ["get", "list"]
- apiGroups: ["*"]
  resources: ["rolebindings"]
  verbs: ["get", "list"]
{{- end -}}