{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
   {{- include "gpu-stats-collector.labels" . | nindent 4 }} 
  name: {{ .Release.Name }}-gpu-stats-collector
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "rolebindings","nodes"]
  verbs: ["get", "list"]
- apiGroups: ["*"]
  resources: ["rolebindings"]
  verbs: ["get", "list"]
- apiGroups:
  - extensions
  resourceNames:
  -  {{ .Release.Name }}-gpu-stats-collector
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{- end -}}
