apiVersion: v1
kind: Service
metadata:
  name: {{ include "datahub-metrics.fullname" . }}
  labels:
    {{- include "datahub-metrics.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    {{- include "datahub-metrics.selectorLabels" . | nindent 4 }}
